# Generated by Django 5.0.7 on 2024-11-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20)),
                ('soft_vendor', models.CharField(max_length=200)),
                ('soft_name', models.CharField(max_length=200)),
                ('soft_version', models.CharField(max_length=200)),
                ('soft_platform', models.DateField()),
                ('soft_type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'soft_tbl_rez',
                'ordering': ('-id',),
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vul_tbl',
            options={'managed': False, 'ordering': ('-id',)},
        ),
    ]
