# Generated by Django 5.0.7 on 2024-11-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_tbl',
            name='soft_platform',
            field=models.CharField(max_length=200),
        ),
    ]
