# Generated by Django 5.0.7 on 2024-11-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_manager', '0004_alter_soft_tbl_soft_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soft_tbl',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='softs', to='cve_manager.vul_tbl', to_field='identifier'),
        ),
    ]
