# Generated by Django 5.1.3 on 2024-12-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_manager', '0005_alter_soft_tbl_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft_type_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_type', models.CharField()),
            ],
            options={
                'db_table': 'tbl_soft_type_rez',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
    ]
