# Generated by Django 5.1.3 on 2024-12-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_manager', '0006_soft_type_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft_name_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_name', models.CharField()),
                ('soft_version', models.CharField()),
            ],
            options={
                'db_table': 'tbl_soft_name_rez',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
    ]
