# Generated by Django 5.1.4 on 2025-01-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_manager', '0007_soft_name_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vul_tbl',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
