# Generated by Django 5.1.6 on 2025-03-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='help_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('topic', models.CharField()),
                ('topic_number', models.SmallIntegerField()),
                ('content', models.CharField()),
            ],
            options={
                'db_table': 'help_tbl',
                'ordering': ('-id',),
                'managed': True,
            },
        ),
    ]
