# Generated by Django 5.1.6 on 2025-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help_tbl',
            options={'managed': True, 'ordering': ('-id',), 'verbose_name': 'Справка по приложению', 'verbose_name_plural': 'Справка по приложению'},
        ),
        migrations.AlterField(
            model_name='help_tbl',
            name='content',
            field=models.TextField(),
        ),
    ]
